"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[palette]
crust = "#181926"
text = "#cad3f5"
mauve = "#c6a0f6"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
blue  = "#8aadf4"
sapphire = "#7dc4e4"
sky = "#91d7e3"
teal = "#8bd5ca"


[[blocks]]
newline = true
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  background = "p:sapphire"
  foreground = "p:crust"
  style = "diamond"
  template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
  type = "os"

  [[blocks.segments]]
  background = "p:sky"
  foreground = "p:crust"
  style = "powerline"
  powerline_symbol = ""
  template = " {{ .UserName }} "
  type = "session"

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  powerline_symbol = ""
  foreground = "p:crust"
  background = "p:teal"

    [blocks.segments.properties]
    style = "folder"

[[blocks]]
type = "prompt"
alignment = "right"
filler = "<p:text,transparent>\u2500"

  

  [[blocks.segments]]
  background = "p:green"
  foreground = "p:crust"
  style = "diamond"
  leading_diamond = "◢"
  template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uF044 {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uF046 {{ .Staging.String }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    fetch_status = true


  [[blocks.segments]]
  type = "python"
  style = "diamond"
  leading_diamond = "◢"
  background = "p:yellow"
  foreground = "p:crust"
  template = "  {{ .Full }} "

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
  foreground = "p:text"
  foreground_templates = ["{{ if gt .Code 0 }}blue{{ end }}"]
  style = "plain"
  template = "\u276f "
  type = "exit"

  [blocks.segments.properties]
    always_enabled = true

[transient_prompt]
background = "transparent"
foreground = "p:text"
template = "{{ if gt .Code 0 }}<p:text>[\ue23a]</>{{ end }} {{ .PWD }} \u276f"

