version = 3
final_space = true

[palette]
  blue = '#8aadf4'
  crust = '#181926'
  green = '#a6da95'
  lavender = '#b7bdf8'
  mauve = '#c6a0f6'
  peach = '#f5a97f'
  sapphire = '#7dc4e4'
  sky = '#91d7e3'
  teal = '#8bd5ca'
  text = '#cad3f5'
  yellow = '#eed49f'

[transient_prompt]
  template = '❯ '
  foreground = 'p:blue'
  background = 'transparent'
  foreground_templates = ['{{ if gt .Code 0 }}p:peach{{ end }}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}}  {{ if .Env.IN_NIX_SHELL }}- shell {{end}}'
    foreground = 'p:crust'
    background = 'p:blue'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .UserName }} '
    foreground = 'p:crust'
    powerline_symbol = ''
    background = 'p:sapphire'
    type = 'session'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    foreground = 'p:crust'
    powerline_symbol = ''
    background = 'p:teal'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  filler = '<p:text,transparent>─'

  [[blocks.segments]]
    leading_diamond = ''
    template = '  {{ .Full }} '
    foreground = 'p:crust'
    background = 'p:yellow'
    type = 'python'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:crust'
    background = 'p:green'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯ '
    foreground = 'p:blue'
    type = 'exit'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}p:peach{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
